Post New Priv
linn/authorisation pull request #86
Opened 2024-01-22 16:09 UTC by RossStewart

Small test and endpoints for creating new privileges. Spoke Oliver through the test and architecture of the request and how it is created.

2024-01-22 16:27 UTC, lewisrenfrew requested changes

2024-01-22 16:27 UTC, lewisrenfrew commented on src/Facade/Services/PrivilegeFacadeService.cs
> +                                    Active = resource.Active
Actually a task for @OliverMclachlan in the morning, can we write a constructor for the Privilege domain class and pass in the name as a parameter instead of this object initializer syntax? you won't need to pass any Active since we just want that to default to true.. i.e. we can just set it as true in the new constructor you add, so all privileges are guaranteed to be born active.

2024-01-22 16:27 UTC, lewisrenfrew commented on src/Facade/Services/PrivilegeFacadeService.cs
> +                                    Id = resource.Id,
We won't know the Id yet - the database will generate one for us so can kill this line

2024-01-22 16:27 UTC, lewisrenfrew commented on tests/Integration/Integration.Tests/PrivilegeModuleTests/WhenPosting.cs
> +            this.resource = new PrivilegeResource { Id = 1, Name = "1", Active = true };
doesnt matter massively, but wouldn't pass and Id or an Active flag here since we don't know Id yet / active will just default to true once we add our new constructor

2024-01-22 16:27 UTC, lewisrenfrew commented on tests/Integration/Integration.Tests/PrivilegeModuleTests/WhenPosting.cs
> +
I would also add a test to check the repository.Add() is being called with the correct data (i.e. just a new privilege with a name field matching the one on the resource)

2024-01-22 16:27 UTC, lewisrenfrew commented on src/Facade/Services/PrivilegeFacadeService.cs
> +                                    Id = resource.Id,
worth double checking this happens in POSTman or something if you haven't already

2024-01-22 16:46 UTC, RossStewart commented on tests/Integration/Integration.Tests/PrivilegeModuleTests/WhenPosting.cs
> +
Made the suggested changes in latest commit. Added a ShouldCallAdd test too but since PrivilegeRepository is currently subbed out I've looked at ANY and changed checking the ID at the bottom to now be the name. If we choose to not sub it out, I can always change this but gives Oliver a good place to get going

2024-01-22 16:57 UTC, richardiphillips commented on tests/Integration/Integration.Tests/PrivilegeModuleTests/WhenPosting.cs
> +            this.resource = new PrivilegeResource { Name = "1" };
this test would be more readable if the name doesn't look like a number

2024-01-22 16:58 UTC, richardiphillips commented on tests/Integration/Integration.Tests/PrivilegeModuleTests/WhenPosting.cs
> +
Choosing not to stub out a repository would be a wild suggestion. You can test that the add is called with the correct object though i.e. has the correct name.

2024-01-22 16:59 UTC, richardiphillips commented on tests/Integration/Integration.Tests/PrivilegeModuleTests/WhenPosting.cs
> +
you could also mock the add action to update the object with an id but there's no need really as you can assume that the common repo is tested elsewhere.

2024-01-22 17:03 UTC, richardiphillips commented on tests/Integration/Integration.Tests/PrivilegeModuleTests/WhenPosting.cs
> +            var resources = this.Response.DeserializeBody<PrivilegeResource>();
resource rather than resources would indicate that you're only expecting one thing back

2024-01-22 17:05 UTC, richardiphillips commented on tests/Integration/Integration.Tests/PrivilegeModuleTests/WhenPosting.cs
> +            resources.Should().NotBeNull();
nothing wrong with this but my personal opinion would be that it's not needed.
it's tested by the next line and there's no need to be defensive in tests.

2024-01-22 17:06 UTC, richardiphillips commented on tests/Integration/Integration.Tests/PrivilegeModuleTests/WhenPosting.cs
> +
Deleted my previous comment as it didn't add anything of interest to Oliver

2024-01-22 17:42 UTC, RossStewart commented on tests/Integration/Integration.Tests/PrivilegeModuleTests/WhenPosting.cs
> +            resources.Should().NotBeNull();
No worries. Will remove. I quite like these in a testing set up as it requires less inspecting of the result when it comes back but can understand why it's redundant.

2024-01-22 17:48 UTC, RossStewart commented on tests/Integration/Integration.Tests/PrivilegeModuleTests/WhenPosting.cs
> +            resources.Should().NotBeNull();
Updates made. If someone okays them I'll make sure to merge them in before start of tomorrow.

2024-01-23 09:30 UTC, lewisrenfrew commented on src/Facade/Services/PrivilegeFacadeService.cs
> +            var privilege = new Privilege
We already have the constructor we need, so just use it here

2024-01-23 10:27 UTC, merged